Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoodreadsDoppelganger.Models;

namespace GoodreadsDoppelganger.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly GoodreadsContext _context;

        public AuthorsController(GoodreadsContext context)
        {
            _context = context;
        }

        // GET: Authors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Authors.Include(a => a.Books).ThenInclude(b => b.Reviews).OrderBy(a => a.FirstName).ThenBy(a => a.LastName).ToListAsync());
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.Include(a => a.Books).ThenInclude(b => b.Reviews)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Biography,BirthDate,ImageUrl")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ConfirmationCreated), new { id = author.Id });
            }
        
            return View(author);
        }

        public async Task<IActionResult> ConfirmationCreated(int? id)
        {
            if (id == null)
                return NotFound();

            var author = await _context.Authors.Include(a => a.Books).FirstOrDefaultAsync(b => b.Id == id);
            if (author == null)
                return NotFound();

            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Biography,BirthDate,ImageUrl")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ConfirmationEdited), new { id = author.Id });
            }
            return View(author);
        }

        public async Task<IActionResult> ConfirmationEdited(int? id)
        {
            if (id == null)
                return NotFound();

            var author = await _context.Authors.Include(a => a.Books).FirstOrDefaultAsync(b => b.Id == id);
            if (author == null)
                return NotFound();

            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = await _context.Authors.FindAsync(id);
            _context.Authors.Remove(author);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ConfirmationDeleted));
        }

        public IActionResult ConfirmationDeleted()
        {
            return View();
        }

        private bool AuthorExists(int id)
        {
            return _context.Authors.Any(e => e.Id == id);
        }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoodreadsDoppelganger.Models;

namespace GoodreadsDoppelganger.Controllers
{
    public class BooksController : Controller
    {
        private readonly GoodreadsContext _context;

        public BooksController(GoodreadsContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString, Genre? genre)
        {
            var books = _context.Books.Include(b => b.Author).Include(b => b.Reviews).OrderBy(b => b.Title);

            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Title.Contains(searchString)).OrderBy(b => b.Title);
            }

            SelectList genres = new SelectList(Enum.GetValues(typeof(Genre)));

            genres.Append(new SelectListItem() { Text = "--Select genre--", Value = null, Selected = true });
            ViewBag.Genres = genres;

            if (genre != null)
            {
                Genre genre1 = (Genre)genre;
                books = books.Where(b => b.Genre == genre1).OrderBy(b => b.Title);
            }

            return View(await books.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var book = await _context.Books.Include(b => b.Author).Include(b => b.Reviews).FirstOrDefaultAsync(b => b.Id == id);
            if (book == null)
                return NotFound();

            return View(book);
        }

        //GET
        public async Task<IActionResult> NewReview(int? id)
        {
            if (id == null)
                return NotFound();

            var book = await _context.Books.Include(b => b.Author).Include(b => b.Reviews).FirstOrDefaultAsync(b => b.Id == id);
            if (book == null)
                return NotFound();

            ViewBag.BookId = book.Id;
            ViewBag.BookTitle = book.Title;
            ViewBag.BookAuthor = book.Author.FirstName + " " + book.Author.LastName;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewReview([Bind("Rating,Text,HasSpoilers,BookId")] Review review)
        {
            review.PublicationDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction("ConfirmationReview", new { id = review.Id});
            }
            return View(review);
        }

        public async Task<IActionResult> ConfirmationReview(int? id)
        {
            if (id == null)
                return NotFound();

            var review = await _context.Reviews.Include(r => r.Book).FirstOrDefaultAsync(r => r.Id == id);
            if (review == null)
                return NotFound();

            return View(review);
        }

        // GET: Books/Create
        public IActionResult Create(int? authorId)
        {
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id");
            if (authorId == null)
                ViewData["SelectedAuthorId"] = -1;
            else
                ViewData["SelectedAuthorId"] = authorId;

            PopulateAuthorsDropDownList();
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,NumberOfPages,ImageUrl,Genre,AuthorId,PublicationDate")] Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ConfirmationCreated), new { id = book.Id });
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", book.AuthorId);
            return View(book);
        }

        public async Task<IActionResult> ConfirmationCreated(int? id)
        {
            if (id == null)
                return NotFound();

            var book = await _context.Books.Include(b => b.Author).FirstOrDefaultAsync(b => b.Id == id);
            if (book == null)
                return NotFound();

            return View(book);
        }


        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var book = await _context.Books.FindAsync(id);
            var book = await _context.Books.Include(b => b.Author).FirstOrDefaultAsync(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            PopulateAuthorsDropDownList();
            return View(book);
        }

        private void PopulateAuthorsDropDownList(object selectedAuthor = null)
        {
            var authorsQuery = from a in _context.Authors
                                   orderby a.LastName
                                   select a;
            ViewBag.Author = new SelectList(authorsQuery.AsNoTracking(), "Id", "FullName", selectedAuthor);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,NumberOfPages,ImageUrl,Rating,Genre,AuthorId,PublicationDate")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ConfirmationEdited), new { id = book.Id });
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Id", book.AuthorId);
            ViewData["Genres"] = new SelectList(GetGenres(), "Genre", "Genre", book.Genre);
            return View(book);
        }

        public async Task<IActionResult> ConfirmationEdited(int? id)
        {
            if (id == null)
                return NotFound();

            var book = await _context.Books.Include(b => b.Author).FirstOrDefaultAsync(b => b.Id == id);
            if (book == null)
                return NotFound();

            return View(book);
        }

        private IEnumerable<Genre> GetGenres()
        {
            return Enum.GetValues(typeof(Genre)).Cast<Genre>();
        }


        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ConfirmationDeleted));
        }

        public IActionResult ConfirmationDeleted()
        {
            return View();
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.Id == id);
        }
    }
}

Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoodreadsDoppelganger.Models;

namespace GoodreadsDoppelganger.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly GoodreadsContext _context;

        public ReviewsController(GoodreadsContext context)
        {
            _context = context;
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Id", review.BookId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Rating,Text,HasSpoilers,BookId,PublicationDate")] Review review)
        {
            if (id != review.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Id", review.BookId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews
                .Include(r => r.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Reviews.Include(r => r.Book).FirstOrDefaultAsync(b => b.Id == id);
            var book = review.Book;
            _context.Reviews.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ConfirmationDeleted), new { id = book.Id });
        }

        public async Task<IActionResult> ConfirmationDeleted(int? id)
        {
            if (id == null)
                return NotFound();
            
            var book = await _context.Books.FindAsync(id);
            if (book == null)
                return NotFound();
            
            return View(book);
        }

        private bool ReviewExists(int id)
        {
            return _context.Reviews.Any(e => e.Id == id);
        }
    }
}

Views/Books/Close.cshtml
<body>    <script type="text/javascript">        window.close();    </script></body>

Views/Books/ConfirmationCreated.cshtml
@model Book

<div class="container-fluid" style="padding:0px">
    <h1>Book successfully created!</h1>
    <hr />
    <h1>@Model.Title</h1>
    <h3>by @Model.Author.FirstName @Model.Author.LastName</h3>
    <div>
        <div style="float:left">
            <img src=@Model.ImageUrl alt=@Model.Title style="max-height:300px;" />
        </div>
        <div style="float:left; margin-left:10px;">
            <p><span class="font-weight-bold">Genre: </span>@Model.Genre</p>
            <p><span class="font-weight-bold">Pages: </span>@Model.NumberOfPages</p>
            <p><span class="font-weight-bold">Publication date: </span>@Model.PublicationDate.ToString("yyyy-MM-dd")</p>

        </div>
    </div>
</div>

<div class="container row" style="margin-left:0px; padding:0px">
    <br />
    <p>@Model.Description</p>
</div>

<a asp-action="Edit" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">
    Edit
</a>
<a asp-action="Delete" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">
    Delete
</a>

Views/Books/ConfirmationDeleted.cshtml
<h2>Book was successfully deleted!</h2>

Views/Books/ConfirmationEdited.cshtml
@model Book

<div class="container-fluid" style="padding:0px">
    <h1>Changes Saved!</h1>
    <hr />
    <h1>@Model.Title</h1>
    <h3>by @Model.Author.FirstName @Model.Author.LastName</h3>
    <div>
        <div style="float:left">
            <img src=@Model.ImageUrl alt=@Model.Title style="max-height:300px;" />
        </div>
        <div style="float:left; margin-left:10px;">
            <p><span class="font-weight-bold">Genre: </span>@Model.Genre</p>
            <p><span class="font-weight-bold">Pages: </span>@Model.NumberOfPages</p>
            <p><span class="font-weight-bold">Rating: </span>@Model.Rating.ToString("#.#") of 5 stars</p>
            <p><span class="font-weight-bold">Publication date: </span>@Model.PublicationDate.ToString("yyyy-MM-dd")</p>

        </div>
    </div>
</div>

<div class="container row" style="margin-left:0px; padding:0px">
    <br />
    <p>@Model.Description</p>
</div>

<a asp-action="Edit" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">
    Edit
</a>
<a asp-action="Delete" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">
    Delete
</a>

Views/Books/Create.cshtml
@model GoodreadsDoppelganger.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1 style="font-weight:bold;">Create new book</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <div>

                    @if (ViewBag.SelectedAuthorId < 0)
                    {
                        <label asp-for="Author" class="control-label" style="font-weight:bold;"></label>
                        <select asp-for="AuthorId" class="form-control inpBox" asp-items="ViewBag.Author">
                            <option value=""></option>
                        </select>
                        <span asp-validation-for="AuthorId" class="text-danger"></span>
                    }
                    else
                    {
                        <label asp-for="Author" class="control-label" style="font-weight:bold;"></label>
                        <select asp-for="AuthorId" class="form-control inpBox" asp-items="ViewBag.Author">
                            <option value="@ViewBag.SelectedAuthorId"></option>
                        </select>
                        <span asp-validation-for="AuthorId" class="text-danger"></span>
                    }
                </div>


            </div>




            <div class="form-group">
                <label asp-for="Title" class="control-label" style="font-weight:bold;">Title</label>
                <input asp-for="Title" class="form-control inpBox" style="background-color:white;" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label" style="font-weight:bold;"></label>
                <input asp-for="Description" class="form-control inpBox" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfPages" class="control-label" style="font-weight:bold;"></label>
                <input asp-for="NumberOfPages" class="form-control inpBox" />
                <span asp-validation-for="NumberOfPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label" style="font-weight:bold;"></label>
                <input asp-for="ImageUrl" class="form-control inpBox" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label" style="font-weight:bold;"></label>
                <select asp-for="Genre" asp-items="Html.GetEnumSelectList<Genre>()" class="form-control inpBox">
                    <option value="">-- Select Genre --</option>
                </select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicationDate" class="control-label" style="font-weight:bold;"></label>
                <input asp-for="PublicationDate" class="form-control inpBox" />
                <span asp-validation-for="PublicationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
    
    
    <div class="form-group">
        <label style="font-weight:bold; padding-left:15px;">or add new author</label>
        <br />
        <a asp-controller="Authors" asp-action="Create" class="btn btn-outline-primary" style="height:40px;">Create new author</a>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Books/Details.cshtml
@model Book

@{
    ViewData["Title"] = "Details";
}
<h1>@Model.Title</h1>
<a asp-controller="Authors" asp-action="Details" asp-route-id="@Model.AuthorId" class="h3" style="color:black">by @Model.Author.FirstName @Model.Author.LastName</a>

<div style="padding:0px; margin-top:2rem">

        <div style="float:left">
            <img src=@Model.ImageUrl alt=@Model.Title style="max-height:300px;" />
        </div>
        <div style="float:left; margin-left:10px;">
            <p><span class="font-weight-bold">GENRE: </span>@Model.Genre</p>
            <p><span class="font-weight-bold">PAGES: </span>@Model.NumberOfPages</p>
            <p><span class="font-weight-bold">RATING: </span>@Model.Rating.ToString("0.0") of 5 stars</p>
            <p><span class="font-weight-bold">PUBLICATION DATE: </span>@Model.PublicationDate.ToString("yyyy-MM-dd")</p>
            <a asp-action="Edit" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">
                Edit
            </a>
            <a asp-action="Delete" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">
                Delete
            </a>
        </div>
</div>

<div class="container row" style="margin-left:0px; padding:0px">
    <br />
    <p>@Model.Description</p>
</div>


<h2 style="font-weight:bold;">Reviews (@Model.Reviews.Count)</h2>

<div>
    <a asp-action="NewReview" asp-route-id="@Model.Id" target="_blank" class="btn btn-outline-primary">
        New Review
    </a>
</div>

<ul class="list-unstyled">
    @foreach (var review in Model.Reviews.OrderByDescending(r => r.PublicationDate))
    {
        <li style="margin-top:40px;">
            <div class="card">
                <div class="card-header" style="background-color:white; border-bottom:hidden">
                    <div style="float:left">

                        <p class="h4" style="font-weight:bold; padding-top:1rem;">
                            @review.Rating OF 5 STARS
                        </p>
                        @if (review.HasSpoilers)
                        {
                            <label class="h5" style="font-weight:bold; margin-right:1rem;">CONTAINS SPOILERS</label>
                            <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" data-target="#collapse-@review.Id" aria-expanded="false" aria-controls="@review.Id">Show</button>
                        }
                    
                    </div>
                    <div style="float:right">
                        <a asp-controller="Reviews" asp-action="Delete" asp-route-id="@review.Id" target="_blank" class="btn btn-outline-secondary">
                            Delete
                        </a>
                    </div>
                </div>
                
                @if (review.HasSpoilers)
                {
            <div class="panel-collapse collapse" id="collapse-@review.Id">
                <hr style="width:96%; margin-left:2% !important; margin-right:2% !important;" />
                <div class="card-body">
                    <p style="font-weight:bold" class="card-text">@review.Text</p>
                </div>
                <div class="card-footer" style="padding-bottom: 0px; background-color:white; border:none">
                    <hr />
                    <p>
                        <small class="text-muted">Published: @review.PublicationDate</small>
                    </p>
                </div>
            </div>
                }

                else
                {
            <div class="panel-collapse collapse show" id="collapse-@review.Id">
                <hr style="width:96%; margin-left:2% !important; margin-right:2% !important;" />
                <div class="card-body">
                    <p style="font-weight:bold" class="card-text">@review.Text</p>
                </div>
                <div class="card-footer" style="padding-bottom:0px; background-color:white; border:none">
                    <hr />
                    <p>
                        <small style="font-weight:bold;" class="text-muted">Published: @review.PublicationDate</small>
                    </p>
                </div>
            </div>
                }
            </div>
        </li>
    }

</ul>

Views/Books/Index.cshtml
@model IEnumerable<GoodreadsDoppelganger.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Books</h1>
<a asp-action="Create" target="_blank" class="btn btn-outline-primary">
    New Book
</a>

<label class="control-label" style="font-weight:bold;"></label>
@using (Html.BeginForm("Index", "Books", FormMethod.Get))
{
<div style="margin-top:2rem;">
    <select class="form-control inpBox col-md-4" style = "float:left; margin-right:1rem;" asp-items="ViewBag.Genres">
        <option value="null">Choose genre</option>
    </select>
    @* @Html.DropDownList("genre", (SelectList)ViewBag.No, new { @class = "form-control inpBox col-md-4", @style = "float:left; margin-right:1rem;" })*@
    <input type="submit" value="Filter" class="btn btn-outline-primary" style="float:left; height:38px;" />
</div>
}

<br />
<div>
    <ul class="list-unstyled" style="margin-top:50px">
        @foreach (var item in Model)
        {
            <li>
                <div class="card mb-3" style="max-height:300px; width:90%; border:none; overflow:hidden;">
                    <div class="row no-gutters">
                        <div class="col-md-2" style="max-width:9rem;overflow:hidden;">
                            <a asp-action="Details" asp-route-id="@item.Id" style="color:black">
                                <img src="@item.ImageUrl" alt=@item.Title style="height:13rem; " />
                            </a>
                        </div>
                        <div class="col-md-10" style="height:13rem">
                            <div class="card-body">
                                <a asp-action="Details" asp-route-id="@item.Id" style="color:black">
                                    <h5 class="card-title text-truncate" style="margin-bottom:0px;">@item.Title</h5>
                                </a>
                                <a asp-controller="Authors" asp-action="Details" asp-route-id="@item.AuthorId" style="color:black;">
                                    <h6 class="card-title" style="margin-top:3px; margin-bottom:7px;">by @item.Author.FirstName @item.Author.LastName</h6>
                                </a>
                                <a asp-action="Details" asp-route-id="@item.Id" style="color:black">
                                    <div class="card-text line-clamp" style="margin-bottom:0px; padding-bottom:0px;">@item.Description</div>
                                </a>
                            </div>
                            <div class="card-footer" style="border:none; background-color:white; padding-top:0px; padding-bottom:0px; margin-bottom:0px; position:static;">
                                <p class="card-text">
                                    <small class="text-muted">Published: @item.PublicationDate.ToString("yyyy-MM-dd") | Rating: @item.Rating.ToString("0.0") of 5 stars (@item.Reviews.Count reviews) | @item.NumberOfPages Pages </small>
                                </p>
                            </div>
                        </div>
                    </div>

                </div>

            </li>
        }

    </ul>
</div>