Controllers/HomeController.cs
using GoodreadsDoppelganger.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GoodreadsDoppelganger.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly GoodreadsContext _context;

        public HomeController(ILogger<HomeController> logger, GoodreadsContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {   
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/Top10Controller.cs
using GoodreadsDoppelganger.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GoodreadsDoppelganger.Controllers
{
    public class Top10Controller : Controller
    {
        private readonly GoodreadsContext _context;
        public Top10Controller(GoodreadsContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> HighestRatedAsync()
        {
            var books = await _context.Books.Include(b => b.Author).Include(b => b.Reviews).ToListAsync();
            var highestRated = books.OrderByDescending(b => b.Rating).Take(10);
            ViewData["Title"] = "Top 10 highest rated books";
            return View("Show", highestRated);
        }

        public async Task<IActionResult> BookClub()
        {
            List<string> titles = new List<string>();
            titles.Add("Girl, Woman, Other");
            titles.Add("The Doors Of Eden");
            titles.Add("The Kite Runner");
            titles.Add("All The Bright Places");
            titles.Add("The Song Of Achilles");
            titles.Add("The Book Thief");
            titles.Add("The Boy Who Followed His Father Into Auschwitz");
            titles.Add("Shadow And Bone");
            titles.Add("Six Of Crows");
            titles.Add("The Fault In Our Stars");

            var books = await _context.Books.Where(b => titles.Contains(b.Title)).Include(b => b.Author).Include(b => b.Reviews).ToListAsync();

            ViewData["Title"] = "Top 10 books for your book club";
            return View("Show", books);
        }

        public async Task<IActionResult> SummerReads()
        {
            List<string> titles = new List<string>();
            titles.Add("Girl, Woman, Other");
            titles.Add("A Thousand Splendid Suns");
            titles.Add("Dear Edward");
            titles.Add("All The Bright Places");
            titles.Add("The Sun And Her Flowers");
            titles.Add("The Binding");
            titles.Add("The Perks Of Being A Wallflower");
            titles.Add("Looking For Alaska");
            titles.Add("Pride And Prejudice");
            titles.Add("Turtles All The Way Down");

            var books = await _context.Books.Where(b => titles.Contains(b.Title)).Include(b => b.Author).Include(b => b.Reviews).ToListAsync();

            ViewData["Title"] = "Top 10 summer reads";
            return View("Show", books);
        }

        public async Task<IActionResult> Poetry()
        {
            List<string> titles = new List<string>();
            titles.Add("Sea Prayer");
            titles.Add("Milk And Honey");
            titles.Add("The Sun And Her Flowers");
            titles.Add("Home Body");
            titles.Add("Chlorine Sky");
            titles.Add("Long Way Down");

            var books = await _context.Books.Where(b => titles.Contains(b.Title)).Include(b => b.Author).Include(b => b.Reviews).ToListAsync();

            ViewData["Title"] = "Top 10 poetry books";
            return View("Show", books);
        }

        public async Task<IActionResult> Anticipated2021()
        {
            List<string> titles = new List<string>();
            titles.Add("Before I Go To Sleep");
            titles.Add("Shadow And Bone");
            titles.Add("Siege And Storm");
            titles.Add("Ruin And Rising");
            titles.Add("A Gathering Of Shadows");
            titles.Add("A Conjuring Of Light");
            titles.Add("A Darker Shade Of Magic");
            titles.Add("The Last Thing He Told Me");
            titles.Add("The Boy Who Followed His Father Into Auschwitz");
            titles.Add("Speaker For The Dead");

            var books = await _context.Books.Where(b => titles.Contains(b.Title)).Include(b => b.Author).Include(b => b.Reviews).ToListAsync();

            ViewData["Title"] = "Top 10 most highly anticipated books of 2021";
            return View("Show", books);
        }

        public async Task<IActionResult> YogaMindfulness()
        {
            
            List<string> titles = new List<string>();
            titles.Add("Light on Yoga: The Bible of Modern Yoga");
            titles.Add("Yoga for Everyone: 50 Poses For Every Type of Body");
            titles.Add("The Little Book of Being: Practices and Guidance for Uncovering Your Natural Awareness");
            titles.Add("Yoga Body: The Origins of Modern Posture Practice");

            var books = await _context.Books.Where(b => titles.Contains(b.Title)).Include(b => b.Author).Include(b => b.Reviews).ToListAsync();
            ViewData["Title"] = "Top 10 books about yoga and mindfulness";
            return View("Show", books);
        }

        public async Task<IActionResult> Quarantine()
        {
            List<string> titles = new List<string>();
            titles.Add("Ender's Game");
            titles.Add("The Giver");
            titles.Add("The Boy Who Followed His Father Into Auschwitz");
            titles.Add("The Hunger Games");
            titles.Add("Six Of Crows");
            titles.Add("Crooked Kingdom");
            titles.Add("Paper Towns");
            titles.Add("And The Mountains Echoed");
            titles.Add("The Tattooist Of Auschwitz");
            titles.Add("Within Without");

            var books = await _context.Books.Where(b => titles.Contains(b.Title)).Include(b => b.Author).Include(b => b.Reviews).ToListAsync();

            ViewData["Title"] = "Top 10 most popular books during quarantine";
            return View("Show", books);
        }

        public async Task<IActionResult> Dieting()
        {
            List<string> titles = new List<string>();
            titles.Add("Fast. Feast. Repeat. : The Comprehensive Guide To Delay, Don't Deny");
            titles.Add("The Switch: Ignite Your Metabolism with Intermittent Fasting, Protein Cycling, and Keto");
            titles.Add("The 30-Minute Mediterranean Diet Cookbook: 101 Easy, Flavorful Recipes for Lifelong Health");

            var books = await _context.Books.Where(b => titles.Contains(b.Title)).Include(b => b.Author).Include(b => b.Reviews).ToListAsync();

            ViewData["Title"] = "Top 10 books about dieting";
            return View("Show", books);
        }
    }
}

Views/Home/About.cshtml
<h2>About</h2>
<div class="grid-container" style="display:inline-flex;">
    <div class="card" style="width:20rem; border:none; overflow:hidden; margin-right:2rem; margin-top:2rem;">
        <img class="card-img-top" src="/images/kenny.jpg" alt="Kenny">
        <div class="card-body">
            <h5 class="card-title">Kenny Boufadene</h5>
            <p class="card-text">Hejsan! :))) </p>
        </div>
    </div>

    <div class="card" style="width: 20rem; border: none; overflow: hidden; margin-right: 2rem; margin-top: 2rem; ">
        <img class="card-img-top" src="/images/robin.jpg" alt="Robin">
        <div class="card-body">
            <h5 class="card-title">Robin Andersson</h5>
            <p class="card-text">Hejsan! :))) </p>
        </div>
    </div>

    <div class="card" style="width: 20rem; border: none; overflow: hidden; margin-right: 2rem; margin-top: 2rem; ">
        <img class="card-img-top" src="/images/amanda.jpg" alt="Amanda">
        <div class="card-body">
            <h5 class="card-title">Amanda Eriksson</h5>
            <p class="card-text">Hejsan! :))) </p>
        </div>
    </div>

    <div class="card" style="width: 20rem; border: none; overflow: hidden; margin-right: 2rem; margin-top: 2rem; ">
        <img class="card-img-top" src="/images/xander.jpg" alt="Xander">
        <div class="card-body">
            <h5 class="card-title">Xander Ek</h5>
            <p class="card-text">Hejsan! :))) </p>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
<h2 style="font-weight:bold">Reading inspiration</h2>

<div class="grid-container" style="display:inline-flex; margin-top:3rem;">

    <div class="card" style="width: 32rem; margin-right:30px; margin-bottom:30px; border:none;">
        <a asp-controller="Top10" asp-action="HighestRated" style="color:black">
            <img class="card-img-top" src="/images/HighestRated.jpg" alt="Highest rated">
            <div class="card-body">
                  <h5 class="card-title">Top 10 highest rated books</h5>
            </div>
        </a>
    </div>

    <div class="card" style="width: 32rem; margin-bottom:30px; margin-right:30px; border:none;">
        <a asp-controller="Top10" asp-action="BookClub" style="color:black">
            <img class="card-img-top" src="/images/BookClub.jpg" alt="Book club">
            <div class="card-body">
                <h5 class="card-title">Top 10 books for your book club</h5>
            </div>
        </a>
    </div>

    <div class="card" style="width: 32rem; margin-bottom:30px; margin-right:30px; border:none;">
        <a asp-controller="Top10" asp-action="Poetry" style="color:black">
            <img class="card-img-top" src="/images/poetry3.jpg" alt="Poetry">
            <div class="card-body">
                <h5 class="card-title">Top 10 poetry books</h5>
            </div>
        </a>
    </div>

    <div class="card" style="width: 32rem; margin-bottom:30px; margin-right:30px; border:none">
        <a asp-controller="Top10" asp-action="SummerReads" style="color:black">
            <img class="card-img-top" src="/images/summer.jpg" alt="Summer reads">
            <div class="card-body">
                <h5 class="card-title">Top 10 summer reads</h5>
            </div>
        </a>
    </div>

    <div class="card" style="width: 32rem; margin-bottom:30px; margin-right:30px; border:none;">
        <a asp-controller="Top10" asp-action="Anticipated2021" style="color:black">
            <img class="card-img-top" src="/images/highlyAnticipated2.jpg" alt="Anticipated 2021">
            <div class="card-body">
                <h5 class="card-title">Top 10 most highly anticipated books of 2021</h5>
            </div>
        </a>
    </div>

    <div class="card" style="width: 32rem; margin-bottom:30px; margin-right:30px; border:none;">
        <a asp-controller="Top10" asp-action="YogaMindfulness" style="color:black">
            <img class="card-img-top" src="/images/yoga3.jpg" alt="Yoga and mindfulness">
            <div class="card-body">
                <h5 class="card-title">Top 10 books about yoga and mindfulness</h5>
            </div>
        </a>
    </div>

    <div class="card" style="width: 32rem; margin-bottom:30px; margin-right:30px; border:none;">
        <a asp-controller="Top10" asp-action="Quarantine" style="color:black">
            <img class="card-img-top" src="/images/quarantine1.jpg" alt="Quarantine">
            <div class="card-body">
                <h5 class="card-title">Top 10 most popular books during quarantine</h5>
            </div>
        </a>
    </div>

    <div class="card" style="width: 32rem; margin-bottom:30px; margin-right:30px; border:none">
        <a asp-controller="Top10" asp-action="Dieting" style="color:black">

            <img class="card-img-top" src="/images/diet.jpg" alt="Dieting">
            <div class="card-body">
                <h5 class="card-title">Top 10 books about dieting</h5>
            </div>
        </a>
    </div>
</div>